# Generated by Django 2.2 on 2020-02-29 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read', to='iotData.Sensor'),
        ),
    ]
