# Generated by Django 2.2 on 2020-02-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0002_auto_20200229_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='channel',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
