# Generated by Django 2.2 on 2020-03-01 00:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0003_sensor_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
