# Generated by Django 2.2 on 2020-03-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0004_reading_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='field1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reading',
            name='field2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reading',
            name='field3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reading',
            name='field4',
            field=models.FloatField(default=0),
        ),
    ]
