# Generated by Django 2.2 on 2020-03-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotData', '0005_auto_20200301_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='field5',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='wqi',
            field=models.FloatField(default=0),
        ),
    ]
